export const SELECTED_NUMBER_OF_PLAYERS = "SELECTED_NUMBER_OF_PLAYERS";
export const NUMBER_OF_CARDS_REQUEST = "NUMBER_OF_CARDS_REQUEST";
export const NUMBER_OF_CARDS_SUCCESS = "NUMBER_OF_CARDS_SUCCESS";
export const NUMBER_OF_CARDS_FAILURE = "NUMBER_OF_CARDS_FAILURE";
